[package]
name = "iced-multi-window"
version = "1.0.0"
edition = "2021"
license = "GPL-3.0"

[dependencies]
iced = { version = "0.12.1", features = ["multi-window"] }
iced-multi-window-macros = { path = "iced-multi-window-macros" }
